language: node_js
node_js:
  - "8"
dist: trusty
cache:
  directories:
    - node_modules
before_install:
  - sudo apt-get update
  - sudo apt-get install zookeeperd
  - sudo apt install -y python-pip
  - pip install zk-shell
  - zk-shell --run-once "create /services ''" localhost
  - zk-shell --run-once "create /services/endpoints ''" localhost 
  - zk-shell --run-once "create /services/endpoints/test ''" localhost
install:
  - npm install
script:
  - npm run test

