language: node_js
node_js:
  - "8"
dist: trusty
cache:
  directories:
    - node_modules
before_install:
  - sudo apt-get update
  - sudo apt-get install zookeeperd
  - /usr/share/zookeeper/bin/zkcli --servers localhost:2181 create /services ""
  - /usr/share/zookeeper/bin/zkcli --servers localhost:2181 create /services/endpoints ""
  - /usr/share/zookeeper/bin/zkcli --servers localhost:2181 create /services/endpoints/test ""
install:
  - npm install
script:
  - npm run test

