language: node_js
node_js:
  - "8"
dist: trusty
cache:
  directories:
    - node_modules
before_install:
  - sudo apt-get update
  - sudo apt-get install zookeeperd
  - wget https://github.com/outbrain/zookeepercli/releases/download/v1.0.10/zookeepercli_1.0.10_amd64.deb
  - sudo apt-get install ./zookeepercli_1.0.10_amd64.deb
  - /usr/bin/zookeepercli --servers=localhost:2181 -c creater "/services/endpoints/test" ""
install:
  - npm install
script:
  - npm run test

