language: node_js
node_js:
  - "8"
dist: trusty
cache:
  directories:
    - node_modules
install:
  - sudo apt-get update
  - sudo apt-get install zookeeperd
  - npm install
script:
  - npm run test

